export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_BUSINESS = 'GET_NEWS_BUSINESS';
export const GET_NEWS_TECHNOLOGY = 'GET_NEWS_TECHNOLOGY';
export const GET_NEWS_SCIENCE = 'GET_NEWS_SCIENCE';
export const GET_NEWS_HEALTH = 'GET_NEWS_HEALTH';
export const GET_NEWS_SPORTS= 'GET_NEWS_SPORTS';
export const GET_NEWS_ENTERTAINMENT = 'GET_NEWS_ENTERTAINMENT';
export const NEWS_ERROR = 'NEWS_ERROR';